on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # check the compilation and run tests
  check:
    runs-on: ubuntu-latest
    container:
      image: gradle:8-jdk21

    steps:
      - uses: actions/checkout@v4

      - name: Java Compilation
        run: sh ./gradlew clean assemble

      - name: Run Tests
        run: sh ./gradlew clean check
