on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # check the compilation and run tests
  check:
    runs-on: ubuntu-latest
    container:
      image: gradle:8-jdk21

    steps:
      - uses: actions/checkout@v4

      - name: Set a non-root user for the workspace
        run: |
          adduser --disabled-password --gecos "" usertest
          chown -R usertest:usertest $GITHUB_WORKSPACE

      - name: Java Compilation
        run: su -s /bin/bash usertest -c './gradlew clean assemble'

      # note that elastic should be run with a non-root user
      - name: Run Tests
        run: su -s /bin/bash usertest -c './gradlew check'
